### ISSUE TITLE
connect timeout

### ISSUE THREAD

**Issue by zh99998** [theturtle32/WebSocket-Node#102]
seems there isn't a connect timeout feature for websocket client...........if remote server choked up..........

**Comment by cubasepp** [comment]
"If the non-native keepalive functionality is chosen"

Is there any example how to implement a custom timeout??

**Comment by ibc** [comment]
Run an interval timer and send custom ping WS messages.

**Comment by cubasepp** [comment]
The Problem is. I add a Firewall rule to drop the packet. So the default timeout is 60 (120)  seconds. But I want to wait only 15 seconds.  Is for the Client Implementation not as a Server. 

I need a custom client timeout... During client.connect
