### ISSUE TITLE
Close handshake: fixed status code and close reason

### ISSUE THREAD

**Issue by braytak** [theturtle32/WebSocket-Node#148]
Currently, WebSocketConnection.close() uses fixed status code (1000) and close reason (Normal connection closure) during the close handshake.

If I understand RFC6455 correctly, on the close handshake (7.1.2) the only requirement is that the status code used be taken from those defined by the standard. Mind you, I may be wrongly considering  these status codes to be meaningful to the server application level rather than WebSocket server level. 

Anyway, my use case is server-server peering. In such cases, being able to convey close status and reason that hint to why peering was torn down (1001-Peer restarting, 1008-Peer policy violation...) would be nice. 

I would appreciate hearing more on this.

**Comment by calebboyd** [comment]
I echo these sentiments. Was facing a ton of re-connection issues in a node client that needed a high reliability. The one line import refactor solved all the issues.

**Comment by theturtle32** [comment]
Was issue was resolved in 0e769dcdf304ae61398ec22bf58153cd812dac8a but I forgot to close it. :)
Closing now. :)
