### ISSUE TITLE
W3CWebSocket#close() lacks code/reason arguments

### ISSUE THREAD

**Issue by ibc** [theturtle32/WebSocket-Node#184]
When I implemented the `W3CWebSocket` shim I used [this version](http://www.w3.org/TR/2011/WD-websockets-20110419/) of the WebSocket API in which `close()` does not accept arguments.

However in the current candidate it accepts "code" and "reason":

http://www.w3.org/TR/websockets/#the-websocket-interface

May be they should be added to the `close()` method?

**Comment by theturtle32** [comment]
That sounds reasonable, I don't expect it would hurt anything to update to the current draft API.  It wouldn't affect backward compatibility.

**Comment by braytak** [comment]
Reasonable!

However if the cited document is referenced as part of the change, this quote from the document itself should be taken into consideration...

> It is inappropriate to cite this document as other than work in progress.
