### ISSUE TITLE
Is anyone else experiencing WebSocketRequest not accounting for X-Forwarded-For as intended? 

### ISSUE THREAD

**Issue by TreadingWater** [theturtle32/WebSocket-Node#190]
I'm admittedly very much a novice at this, so I suspect its something i'm doing wrong not WebSocket-Node, but just incase i'm wrong here goes:

I have a server hosted by openshift which logs request.headers['x-forwarded-for'] for every http request it receives and it is correctly showing client ip addresses.  

However logging WebSocketRequest.remoteAddress in a similar manner always shows my NodeJS server ip address, furthermore logging WebSocketRequest.httpRequest.headers['x-forwarded-for'] shows undefined.

I’m completely out of ideas to what could be causing this, I even set ignoreXForwardedFor to false even though it should be by default just incase.  

Anyway, just thought I should ask incase its not me and this is actually an issue.

**Comment by theturtle32** [comment]
I'll have to test, I haven't really verified this in quite some time.  It probably would be useful to write a test for this specifically.

**Comment by TreadingWater** [comment]
Sorry I didn't reply to this sooner, i've written the following test:

---
"use strict";

var http  =  require("http");
var webSocketServer = require('websocket').server;

var server_port = process.env.OPENSHIFT_NODEJS_PORT || 8080;
var server_ip_address = process.env.OPENSHIFT_NODEJS_IP || '127.0.0.1';

    
    var ssHTTPServer = http.createServer(function (request, response) {
        console.log("Receiving HTTP request");
        
        // returns the correct IP on open shift
        console.log("request.headers['x-forwarded-for'] = " + request.headers['x-forwarded-for']);
        
        response.writeHead(200, {"Content-Type": "text/html"});
        response.write("<body>Http request recieved.  Now sending websockets request <script>var connection = new WebSocket('ws://INSERTADDRESS:INSERTPORT');</script></body>");
        response.end();
    });
    
    
    ssHTTPServer.listen(server_port, server_ip_address, function () {
        console.log("Listening on " + server_ip_address + ", server port " + server_port);
    });
    
    console.log("HTTP server has started");
    
    var ssWebSocketServer = new webSocketServer({httpServer: ssHTTPServer, ignoreXForwardedFor: false});
    
    console.log("Websocket server has started");
    
    ssWebSocketServer.on('request', function (request) {
        
        console.log("Websocket connection request recieved");
        // returns incorrect ip on open shift
        console.log("WebSocketRequest.remoteAddress = " + request.remoteAddress);
        // undefined on open shift 
        console.log("WebSocketRequest.httpRequest.headers['x-forwarded-for'] = " + request.httpRequest.headers['x-forwarded-for']);
        
        var connection = request.accept(null, request.origin);
        
        console.log('WebSocket Connection accepted.');
        // returns incorrect ip on open shift
        console.log("Connection Remote Address = " + connection.remoteAddress);
        // returns incorrect ip on open shift
        console.log("Connection Socket Remote Address = " + connection.socket.remoteAddress);
        
    });
---

I tested this on open shift and got the same results, It can only find x-forwarded and the correct address via the the HTTP request, as evidenced by its second console log being correct.   I also did another test in which I hosted locally and got a friend to visit my IP, unsurprisingly all IP's returned were correct and x-forwarded-for was undefined in all cases, as it should be to my understanding.  

I'm beginning to wonder if this is just open shift not using an x-forwarded-for header or something... but then why does the http request header have x-forwarded-for defined when WebSocketRequest.httpRequest.headers does not?

**Comment by codelegend** [comment]
I have faced the same issue with Sockjs too. I think it is a problem with Openshift routing
