### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Pixmap** [theturtle32/WebSocket-Node#192]
I have a memory leak on the server if I use websocket.
My server code:
```
var http = require("http");
var webSocketServer = require('websocket').server;

var server = http.createServer(function(request, response) {
    response.writeHeader(404);
    response.end();
});

var wsServer = new webSocketServer({ httpServer: server, autoAcceptConnections: false });

wsServer.on('request', function (request) {
  try {
    var connection = request.accept(null, request.origin);
    connection.on('close', function (reasonCode, description) {
    });
  } catch (error) {
  }
});
server.listen(51000);
```
Client html:
```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
</head>
<div id="login">
  
    <input type="button" name="Test" value="test" onclick="test()"/>
    <script>
    var isConnected = 0;
    var ws;
    function test() {
     if(isConnected)
     {
       ws.close();
       delete ws;
       isConnected = 0;
     } else {
       var serverAddress = "127.0.0.1:51000";
       ws = new WebSocket("ws://"+serverAddress);
       isConnected = 1;
     }
   }
   </script>
</div>
</html>
```

I used Node v.0.12.0
Websocket v.1.0.17
To detect leaks I used ProcessExplorer v.16.03

When I started server PrivateBytes = 17864 and WorkingSet = 21252
After starting the server, I has opened the client page in the browser firefox and has clicked on test button 100 times. After this PrivateBytes = 23572 and WorkingSet = 23324
I waited 10 minutes, but the values were not less. If I keep pressing the button, values only grow.

Before I create a new issue I has read: #77, #105, #110, #167, but could not find an explanation.

Any ideas what may be associated with this leak?

**Comment by QianJin2013** [comment]
how about you add on('message')..... and on('error',.... ?

**Comment by Pixmap** [comment]
I has added
```
  connection.on('message', function (message) {
  });
  connection.on('error', function (error) {
  });
```
but it did not change anything

**Comment by theturtle32** [comment]
The memory growth you're describing is so small (just a few KiB) that the GC may not be bothering to do a sweep.  I'm not aware of all the intricacies of how V8's GC works, but this test is, frankly, inconclusive.

Instead of clicking the button 100 times, why don't you program it to automatically connect and disconnect several thousand times?  You can also do that without using the browser by running a separate node process as the client.

Additionally, try using the Heapdump module to capture snapshots before and after the run, which you can load into Chrome's profiler and try to identify which objects are sticking around.

**Comment by ibc** [comment]
> The memory growth you're describing is so small (just a few KiB) that the GC may not be bothering to do a sweep.  I'm not aware of all the intricacies of how V8's GC works, but this test is, frankly, inconclusive.

Exactly. The very same happens in Ruby EventMachine and other languajes/frameworks/platforms.

**Comment by Pixmap** [comment]
Client without browser:
```
var WebSocketClient = require('websocket').client;

function Test() {
  var client = new WebSocketClient();
  
  client.on('connectFailed', function(error) {
    console.log('Connect Error: ' + error.toString());
  });

  client.on('connect', function(connection) {
      console.log('WebSocket Client Connected');
   
      connection.close();
      connection.on('error', function(error) {
          console.log("Connection Error: " + error.toString());
      });
      connection.on('close', function() {
          console.log('echo-protocol Connection Closed');
      });
      connection.on('message', function(message) {
          if (message.type === 'utf8') {
              console.log("Received: '" + message.utf8Data + "'");
          }
      });
  });

  client.connect('ws://localhost:51000/');
  delete client;
}

for(var i = 0; i < 100000; ++i)
Test();
```
Before start client:
PrivateBytes=17852
WorkingSet=21252

After client finished:
PrivateBytes=710240
WorkingSet=710352

**Comment by theturtle32** [comment]
This is invalid testing methodology.  Just to make sure, I ran the tests myself, watching the memory usage of the server process and did over a million connects/disconnects from other client processes, and there was no long-term growth of the process's memory consumption once it stabilized.

**Comment by QianJin2013** [comment]
Agree.
as my practice  of using websocket lib in nodejs, I could not find such
problem explicit memory leak,
 memory reached a limit of several hundred mob then decreased by garbage
collector.

2015年3月11日水曜日、Brian McKelvey<notifications@github.com>さんは書きました:

**Comment by Pixmap** [comment]
Your answers are not convincing. I have given you a concrete example that demonstrates the problem. If you believe that it contains a mistake, correct it, or at least show your client that establishes 100 000 connections and memory is not leaking.

**Comment by Pixmap** [comment]
I started my client several times to see how the server will drop but the memory was cleared when it was more than 1.1 Gb. I think the problem may indeed be associated with the work of GC. 

Thanks for the answers!
