### ISSUE TITLE
trivial problem: passing number to connection.send() cause crash in ._debug due to no .slice method 

### ISSUE THREAD

**Issue by QianJin2013** [theturtle32/WebSocket-Node#195]
The connection.send(data) is designed to handle any type which have toString method, such as Number(1), {a:1},  etc..., all right?
BUT: if i really pass a Number(1) to it, it crashes at first line in the sendUTF method.

Obviously caused by data.slice(0,80), so it should be checked, i know it's boring.

WebSocketConnection.prototype.sendUTF = function(data, cb) {
     this._debug('sendUTF: %s', data.slice(0,80) + '|...');

better be
-->     data = String(data)
-->     this._debug('sendUTF: %s', data.slice(0,80) + '|...');
BTW, later data.toString() is not necessary.

If you have time, you can check it.

**Comment by theturtle32** [comment]
Good catch!  I accidentally introduced this bug in 5f0c4901ac646c50d89db6a728540204eec8593c when I added some extra debugging.

**Comment by theturtle32** [comment]
Just released v1.0.18 including this fix.
