### ISSUE TITLE
W3CWebSocket doesn't handle connection failures messages

### ISSUE THREAD

**Issue by Ornro** [theturtle32/WebSocket-Node#198]
The W3CWebSocket implementation catches the 'connectFailed' event from the client with the following function :
``` javascript
this._client.on('connectFailed', function() {
    onConnectFailed.call(self);
});
```

The client emits error events like this:
``` javascript
function handleRequestError(error) {
    self._req = null;
    self.emit('connectFailed', error);
}
```
The error passed to the W3CWebSocket  is not transmitted further down, it make errors harder to identify when coding. Is it made on purpose ?

**Comment by theturtle32** [comment]
Yes, it is on purpose, to match the W3C specification. In the spec, there is no detail given about the exact failure cause.
