### ISSUE TITLE
Expose events to facilitate manual ping/pong handling and tracking.

### ISSUE THREAD

**Issue by mkzh** [theturtle32/WebSocket-Node#205]
Pings, as specified in the RFC "may serve either as a keepalive or **as a means to verify that the remote endpoint is still responsive**". Currently when a Websocket connection sends out a ping, it does not make any attempt to remember that request. So when the pong eventually returns the connection [does essentially nothing](https://github.com/theturtle32/WebSocket-Node/blob/481648a7c8fe339f2dea64f84b66ba9fc2765540/lib/WebSocketConnection.js#L611-L613). This makes it difficult for the client to verify that a connection is active without setting "assembleFragments" to false and manually filtering for pongs (while wastefully assembling packets himself).   

I think the easiest fix to this problem is to have the connection emit a "sendping" when a ping is sent and a "pong" when a pong is received, or something similar. The client is then able to tell when a particular peer is unresponsive, and possibly try to reconnect to or drop the peer.

**Comment by theturtle32** [comment]
I see what you mean, and I agree it may be useful to have a `pong` event when a pong is received. I'm hesitant about the `sendping` event though. Mostly, I feel like if you're sending pings that you want to track, you should be the one triggering the sending. And if you're the one sending the pings, you don't need an event to tell you what you just did.

The library already has a `ping(data)` method on the WebSocketConnection object, so you can already send arbitrary pings. We just need to add the `pong` event, which should only be emitted if event listeners for the `pong` event have been added.

I'm open to a pull request for this. It should be pretty trivial to add, and you've already identified the code location where it would need to be implemented.

**Comment by theturtle32** [comment]
Also, if we add a `pong` event, we should add a matching `ping` event as well, along with a way for the event handler to optionally bypass the built-in pong response functionality. This could be achieved by passing a `cancel` function as the second parameter to the `ping` event.
