### ISSUE TITLE
Cannot set binaryType to 'blob' on w3cwebsocket

### ISSUE THREAD

**Issue by Densaugeo** [theturtle32/WebSocket-Node#209]
Running this code:

~~~
var websocket = require('websocket');
var test = new websocket.w3cwebsocket('ws://localhost:8080/');
test.binaryType = 'blob';
~~~

Gives this error:

~~~
SyntaxError: just "arraybuffer" type allowed for "binaryType" attribute
~~~

However, 'blob' is an allowed binaryType in the browser (at least in Firefox, haven't checked the others).

Not sure if I am missing something (I haven't used this library before).

**Comment by ibc** [comment]
Chrome does not support "blob" type yet, but it does not matter since when running in the browser this library exposes nothing but just the native WebSocket.

The reason for no "blob" support is that Node does not support `Blob` types.
