### ISSUE TITLE
Altering closeTimeout property of websocket client

### ISSUE THREAD

**Issue by majorgilles** [theturtle32/WebSocket-Node#210]
I didn't find any way to do this in the source code. I saw the websocket client has a constructor with a config parameter. Is it alterable by the user?

Is there a way to prevent the socket from closing automatically? I'm trying to communicate with a speech to text service which can have some delays before reporting results.

**Comment by amasad** [comment]
I'm having the same issues with the closing delay.

**Comment by p4r4n0id** [comment]
Is there any further information regarding this? How to configure this parameters in NodeJS?

**Comment by theturtle32** [comment]
@majorgilles @amasad @p4r4n0id - you set it the same way as you would for the server:
```javascript
var client = new WebSocketClient({
  closeTimeout: 15000
});
```

However, this property has nothing to do with what you're probably thinking it does. It's not at all related to keep-alive functionality or closing idle connections.

In the [documentation](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketServer.md), *closeTimeout* is described as:
> The number of milliseconds to wait after sending a close frame for an acknowledgement to come back before giving up and just closing the socket.
