### ISSUE TITLE
Ping event can not be fired

### ISSUE THREAD

**Issue by suyuan1203** [theturtle32/WebSocket-Node#213]
I'm using 1.0.21. It seems WebSocketConnection.ping event does't work.

The code is simple.
```
var client = new WebSocketClient();
client.on('connect', function(connection) {
    connection.ping('1');
});
```

I expect the ping event is fired at the server side, but it doesn't.

From the doc

> ping

> function(cancel, data)

>This event is emitted when the connection receives a ping from the peer. cancel is a function taking no arguments that when called prevents the WebSocketConnection object from automatically replying with a pong. data is the binary payload contained in the ping frame.

Code from WebSocketConnection.js
```
case 0x09: // WebSocketFrame.PING
            this._debug('-- Ping Frame');
            this.pong(frame.binaryPayload);
            break;
```

It seems once there's a ping, the server just sends back a pong, without fire the 'ping' event.

Is this a unfinished feature?

**Comment by theturtle32** [comment]
Sorry for the late response. No, this is implemented: https://github.com/theturtle32/WebSocket-Node/blob/2d228f8d13ed3cd4bbb2ef5431b802ecbd42d2e9/lib/WebSocketConnection.js#L618-L639

```javascript
        case 0x09: // WebSocketFrame.PING
            this._debug('-- Ping Frame');

            if (this._pingListenerCount > 0) {
                // logic to emit the ping frame: this is only done when a listener is known to exist
                // Expose a function allowing the user to override the default ping() behavior
                var cancelled = false;
                var cancel = function() { 
                  cancelled = true; 
                };
                this.emit('ping', cancel, frame.binaryPayload);

                // Only send a pong if the client did not indicate that he would like to cancel
                if (!cancelled) {
                    this.pong(frame.binaryPayload);
                }
            }
            else {
                this.pong(frame.binaryPayload);
            }

            break;
```

**Comment by theturtle32** [comment]
At the time you filed this, it's possible that the new version containing that feature hadn't yet been published to NPM.  Sorry for the confusion!

https://github.com/theturtle32/WebSocket-Node/commit/2d228f8d13ed3cd4bbb2ef5431b802ecbd42d2e9
