### ISSUE TITLE
Are there any callback supports?

### ISSUE THREAD

**Issue by kousha-icracked** [theturtle32/WebSocket-Node#216]
For example, is there anyway to get the following support?

__Client:__

    connection.send("someData", function (returnedData) {
         // Returned by the server
         console.log(returnedData);
    });
  

__Server:__

    connection.on('message', function (message, cb) {
        // Message contains "someData" string
        // Use cb to send data back to the call
        cb("Here you go sir");
    });

The pattern above currently doesn't do anything. The callback inside the `client` is intended as an error handling, i.e. `returnedData` is actually the error if data was not sent down the line.

**Comment by theturtle32** [comment]
No. What you're describing is higher level functionality, and is not part of the WebSocket protocol. This library only provides an API around an implementation of the WebSocket protocol itself. Additional enhanced functionality should be implemented in your own code, or by another library that would in turn use this library internally.
