### ISSUE TITLE
Reusing WebSocket-Connection in Virtual Environments

### ISSUE THREAD

**Issue by p4r4n0id** [theturtle32/WebSocket-Node#217]
Hey there,

i'm currently experiencing problems using this websocket-packet in a virtual environment. Without any further information about the VM-Software i'm analyzing my log-files and experiencing issues with reused sessions. So this is the timeline:

- User 1 connects to websocket and gets an connection-id (increment a number in an array: 333) and sends an Location (83)
- User 2 connects to websocket and gets the same connection-id (333) and sends an Location (99)

after that the connection to User 1 is broken. 

I think this problem is based on an failure in the identification process and the only way to solve this for me is to deactivate this "reuse" of connections. Is there are possible way to deactivate this?

Best Regards

**Comment by ibc** [comment]
WebSocket-Node does not provide any "connection reuse" feature. In fact that is out of the scope of a WS stack.

It is up to your application to define what "connection reuse" is if you need that.
