### ISSUE TITLE
Can`t connect due to "Sec-WebSocket-Protocol header"

### ISSUE THREAD

**Issue by ccioloca** [theturtle32/WebSocket-Node#220]
When I try to connect to hitbox.tv ws I'm getting this error:

Connect Error: Error: Expected a Sec-WebSocket-Protocol header.

Does anyone know a solution fot this?

**Comment by ibc** [comment]
This is not an issue nor a bug in this library. Please refer to the [WebSocket RFC](https://tools.ietf.org/html/rfc6455) and, specially, to the W3 [WebSocket API](https://www.w3.org/TR/2011/WD-websockets-20110419/) and search for "subprotocol", "sub-protocol" or just "protocol".
