### ISSUE TITLE
exports DEBUG="*" + request.accept triggers an error

### ISSUE THREAD

**Issue by Incubatio** [theturtle32/WebSocket-Node#221]
For the first time, I met a bug with that nice lib.
It's nothing really major, but because of the nature of the bug and the obscure error logs,
it got me stuck for 20 minutes ...

**Error log:** 
```bash
timers.js:555
    timeSinceLastActive = now - cur._idleStart;
                                   ^

TypeError: Cannot read property '_idleStart' of null
    at Timer.unrefTimeout (timers.js:555:36)
```

**How to reproduce:**
in your shell, where you start your server:
``exports DEBUG="*"``
Then simply connect to your websocket server with any client.
The server will break when accepting the request:
``request.accept('<protocol>', request.origin);``

**Cause:**
Bug seems to be caused by the following line:
(lib/WebsocketConnection.js line 107): ``this.socket.setTimeout(0);``

**Comment by theturtle32** [comment]
What version of Node are you running?

**Comment by theturtle32** [comment]
This is most definitely a bug in Node core for whatever version of Node you're running.
