### ISSUE TITLE
Unexpected token :

### ISSUE THREAD

**Issue by piotrgondek** [theturtle32/WebSocket-Node#222]
Hello everybody,

I want use to **websocket** in my application using stompjs (stompjs has dependency to websocket). I'm using webpack to build final js file.
In one of my scripts I added var Stomp = require('stompjs'); and after this I had error

```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: ./~/stompjs/~/websocket/package.json
Module parse failed: myAppLocation/node_modules/stompjs/node_modules/websocket/package.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "_args": [
|     [
|       "websocket@^1.0.22",
 @ ./~/stompjs/~/websocket/lib/version.js 1:17-43
```

It is a very strange issue for me because **version.js** file has only one line:
``
module.exports = require('../package.json').version;
``

How can I fix this behaviour?

Thank you for respond.

**Comment by ibc** [comment]
AFAIK webpack does not allow `require(SOME_LIB).foo`, so this would fail:

```js
module.exports = require('../package.json').version;
```

**Comment by ibc** [comment]
You may try to modify the above code as follows:

```js
var package = require('../package.json');

module.exports = package.version;
```

**Comment by piotrgondek** [comment]
Thank you, I will add pull request to stompjs.
