### ISSUE TITLE
FastBufferList.js does not release reference to last buffer in list when emptied

### ISSUE THREAD

**Issue by JensEggers** [theturtle32/WebSocket-Node#223]
When FastBufferList.advance() empties the buffered data, head.buffer is set to null but last.buffer is left alone. This causes a buffer reference to linger, and this in turn can prevent a large SlowBuffer instance internal to Node.js from being cleaned up.

This is not a permanent leak as the next write to the FastBufferList instance will update last.buffer.

**Comment by theturtle32** [comment]
Wow, sharp catch. Thanks for the fix. What led to this discovery?

**Comment by JensEggers** [comment]
Thanks :-)

We had a situation on a small embedded device using a pool of websocket clients, where not cleaning up completely after a socket close or error (while keeping the websocket client instance alive) caused excessive memory use. Keeping a pool of temporarily inactive websocket clients multiplied this.

We found the culprit by comparing some heap dumps, where it became clear that the 'last' variable was the sole remaining reference keeping a SlowBuffer alive.
