### ISSUE TITLE
Request Router Example

### ISSUE THREAD

**Issue by iKoala** [theturtle32/WebSocket-Node#228]
In the readme it said we should see libwebsockets-test-server.js in the test folder, but there is not such file in the test folder.
May I know where should I check the request router example?

**Comment by theturtle32** [comment]
Well, it's there, it's just one level deeper in the scripts folder inside the test folder.

https://github.com/theturtle32/WebSocket-Node/blob/master/test/scripts/libwebsockets-test-server.js
