### ISSUE TITLE
Dependency on old nan version causes compile issues with Node 6.1.0

### ISSUE THREAD

**Issue by RickBullotta** [theturtle32/WebSocket-Node#230]
Attempting to install websocket on Node 6.1.0 leads to a number of compile issues related to incompatibilities in Nan 2.2.3 and Nan 2.0.X.

**Comment by erhhung** [comment]
I just installed on OS X under Node 6.1.0 and had no issues--very clean install. It was using nan 2.0.9.
BTW, "npm info nan" does not show 2.2.3 to be a published version.

**Comment by theturtle32** [comment]
Just updated the nan dependency and published a new version, v1.0.23
