### ISSUE TITLE
As I send cookie WebSocketClient?

### ISSUE THREAD

**Issue by mhinostroza** [theturtle32/WebSocket-Node#233]
As I send cookie WebSocketClient ?, I'm having problems with nodejs to connect from Traccar.
var WebSocketClient = require('websocket').client;

var client = new WebSocketClient();

client.on('request', function (request) {
    console.log("Websocket connection request recieved");
});

var session =  {
    Cookie:"JSESSIONID=for6iklifwqjrlr7lf0qicup"
};
client.connect('ws://localhost:8082/api/socket', session);

**Comment by ibc** [comment]
Sorry, the above code does not make much sense. Check the API doc please.
