### ISSUE TITLE
"Error: Socket hang up" when trying to connect to arbitrary ws servers

### ISSUE THREAD

**Issue by cyclingLinguist** [theturtle32/WebSocket-Node#234]
I have ran the example code for a client and server and they communicate just fine over localhost. But when I try to use the client to connect to an arbitrary server (which I know supports websockets) say a slither.io server, the connection hangs up, which I read indicates that no response was received from the server and the connection timed itself out.

I'm sure this is me just not understanding properly how to implement a general purpose client and not an issue with the code, but I thought someone here could clarify my problem pretty easily.

Sorry if this isn't the right place to post this problem.

**Comment by ibc** [comment]
The server may require a specific Origin header or Cookies.

**Comment by cyclingLinguist** [comment]
Thanks! With your help and some detailed comparison of the packets my browser sent vs the packets websocket-Node sent I was able to figure it out! Yeah, the server did require a specific origin header. Thanks so much!

**Comment by ibc** [comment]
Great ;)
