### ISSUE TITLE
Intermittent "Error: Sec-WebSocket-Accept header from server didn't match expected value of X"

### ISSUE THREAD

**Issue by cyclingLinguist** [theturtle32/WebSocket-Node#235]
More often than not when attempting to connect to a server I get "Error: Sec-WebSocket-Accept header from server didn't match expected value of X" Where X is a key. The really odd thing is sometimes the connection works without a hitch. 

How can WebSocket-Node only sometimes be generating the wrong key? Or is it likely that the server is generating the wrong key? Could it be using a different encryption or version?

**Comment by theturtle32** [comment]
After several years in regular production use, I'm pretty confident that websocket-node isn't intermittently generating the wrong key. But if you feel strongly that it is, please provide more substantive information about your situation including:

- What kind of server you're connecting to
- Do you control the server?
- Code example that doesn't work consistently
- Platform and version information

**Comment by aeisenberg** [comment]
I am receiving this error intermittently as well. I'm trying to debug the reason why it might be happening. Although it looks like a user error, I do believe the library could provide some better error messages in this particular case.

It looks like we receive this if `connect` is called twice on the same client without disconnecting either one of them.

So, this snippet will reliably cause the error:
```

let opts = 'ws://mywebsocket';

let WebsocketClient = require('websocket').client;
let client = new WebsocketClient();

client.on('connect', msg => console.log('Yay!'));
client.on('connectFailed', msg => console.error(msg));

client.connect(`ws://${opts}`);
client.connect(`ws://${opts}`);
```
This only fails if the on 'connect' handler for the first connection is called after the call to the second connect.


Now, I think it makes sense that this doesn't work, but it seems to me that the client should fail fast if it already has a connection.  In other words, it seems to me that the second call to `client.connect()` should throw an error if a previous call to `connect()` has happened and there is not yet a response.

**Comment by aeisenberg** [comment]
One possible solution would be to move the nonce creation code into the constructor of the client. So, this would move to the constructor:

    var nonce = new Buffer(16);
    for (var i=0; i < 16; i++) {
        nonce[i] = Math.round(Math.random()*0xFF);
    }
    this.base64nonce = nonce.toString('base64');

The side effect would be that all connections of the same client would handshake with the same nonce. Is this a bad thing? Alternatively, you could store one nonce per server URL connected to. And each connection to the same URL with the same client would use the same nonce.

**Comment by aeisenberg** [comment]
Apologies for the noise, but one more thing.  It seems like calling `client.abort()` in between the first and second calls to connect will avoid the error when the first connection call returns.

Since this situation will *always* result in an error unless `abort` is called, it seems that the client should throw an error. And it would be a fairly simple fix from what I can see.
