### ISSUE TITLE
WebSocket Install Errors

### ISSUE THREAD

**Issue by thirdlastletter** [theturtle32/WebSocket-Node#238]
Hi;

I am trying to install WebSocket and I am getting following errors:

C:\Program Files\nodejs>npm install websocket
npm ERR! tar.unpack untar error C:\Users\isw\AppData\Roaming\npm-cache\websocket
\1.0.23\package.tgz
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "websocket"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path C:\Program Files\nodejs\node_modules\websocket
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall mkdir

npm ERR! Error: EPERM: operation not permitted, mkdir 'C:\Program Files\nodejs\n
ode_modules\websocket'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, mkdir 'C:\Program Files\node
js\node_modules\websocket']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: 'C:\\Program Files\\nodejs\\node_modules\\websocket',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: 'C:\\Program Files\\nodejs\\node_modules\\websocket',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\fstre
am\\lib\\dir-writer.js:35:25',
npm ERR!      'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\mkdir
p\\index.js:47:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "websocket"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! path C:\Program Files\nodejs\npm-debug.log.3030439379
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open

npm ERR! Error: EPERM: operation not permitted, open 'C:\Program Files\nodejs\np
m-debug.log.3030439379'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, open 'C:\Program Files\nodej
s\npm-debug.log.3030439379']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'C:\\Program Files\\nodejs\\npm-debug.log.3030439379' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Program Files\nodejs\npm-debug.log

I have downloaded Python and I have Visual Studio.

Does anyone have a solution?

**Comment by ibc** [comment]
It seems that your user has no write permissions on `C:\Program Files\nodejs\`, it **clearly** says "Please try running this command again as root/Administrator.". Did you read it?

Why don't you run `npm install websocket` on a path in which your current user has write permissions?

> Does anyone have a solution?

Please, do not ask for "solutions" when there is no a confirmed problem.
