### ISSUE TITLE
How to send message to specific client?

### ISSUE THREAD

**Issue by hisune** [theturtle32/WebSocket-Node#242]
In socket.io, I can do like this:
```js
io.to(socket.socket_id).emit(
	event,
	msg
);
```

But node websocket do not have socket id, Any ideas?

**Comment by ibc** [comment]
This is a WebSocket server, not a "easy framework to build realtime apps" (such as socket.io).

Yo must read the doc and build your custom app on top of this `websocket` module. This is not yet another socket.io. Please read the doc.
