### ISSUE TITLE
abort() sometimes is quite slow (more than 20 seconds)

### ISSUE THREAD

**Issue by rebrec** [theturtle32/WebSocket-Node#244]
When spawning multiple parallel Websocket clients, and adding a timeout code like this one : `setTimeout(() => {this.ws.abort()}, 3000);`

I sometimes have to wait more than 20 seconds to get an event ('close', 'error', whatever else).

Aren't there a way to get a 'close' or 'error' event faster please ?

**Comment by theturtle32** [comment]
Can you paste a code sample of how you are spawning these multiple parallel clients?

**Comment by rebrec** [comment]
Sorry I took times to answer, this was a problem of myself.
I close the Issue
