### ISSUE TITLE
How to set a sub route for websocket server?

### ISSUE THREAD

**Issue by Ewebalvin** [theturtle32/WebSocket-Node#245]
Hi , this is how I use the websocker server.
```
  var server = http.createServer(self);

  self.server.listen('8080');

  var WebSocketServer = require('websocket').server;
     var wsServer = new WebSocketServer({
      httpServer: app.server,
      autoAcceptConnections: false
  });
```
The URL for http is : http://localhost:8080, for websocket is: ws://localhost:8080.
For some reasons, I need to set URL for websocket to: ws://localhost:8080/ws

How should I do it?

**Comment by ibc** [comment]
The `WebSocketServer` instance just listens for data coming from the given `httpServer` server, nothing else. If you want to validate the URL of the WebSocket GET request you must do it manually by inspecting the `WebSocketRequest` before validating the connection:

https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketRequest.md#properties
