### ISSUE TITLE
Can Connection#sendBytes() send additional data?

### ISSUE THREAD

**Issue by agomat** [theturtle32/WebSocket-Node#248]
Hello. I am using **sendBytes()** to send severals file to a client. The issue is that I have to put in an envelope, so it can be identified in the client. E.g.: I need to send a binary file and also it's filename.

The first answer would most likely be, to put the binary data in base64 and just push it to JSON and then send all data via sendUTF8(). Drawback: base64 --> data increase

Any other suggestions? Maybe using another channel for the purpose. I'd need to open a second websocket for that, right? Or maybe using the binay.length (or sha1) itself as key (ugly) to identity the file .

Thanks

**Comment by ibc** [comment]
Up to you. You can send both UTF8 and binary messages over the same WS connection, but the receptor must be ready to understand them. For example, you may send first a UTF8 file containing a JSON with the filename and so on, and then the binary message containing the file itself.
