### ISSUE TITLE
WebSocketClient close

### ISSUE THREAD

**Issue by favio41** [theturtle32/WebSocket-Node#257]
Hi, Anyone knows how to close the WebSocketClient?

Looking into the [documentation](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketClient.md) I can't found anything.

I don't want to restart the service each time that I want to kill the WebSocket.

**Comment by theturtle32** [comment]
The close method is part of WebSocketConnection, not WebSocketClient, which returns a WebSocketConnection object when emitting the connect event.
