### ISSUE TITLE
WebSocketServer cannot receive amount of data more than maxReceivedFrameSize setting.

### ISSUE THREAD

**Issue by VooVoo01** [theturtle32/WebSocket-Node#260]
I can't send data which more than **maxReceivedFrameSize** setting (by default 0x10000 = 64Kb) from WEB browsers to the WebSocketServer. I've tried to do this from any browsers via http and https, the results are same.
The [documentation ](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketServer.md#server-config-options) says “_single frame messages will also be limited to this maximum_”. Do the browsers send data in single frame? I'm not sure about it.
There are many information about browsers` WebSocket interface and frames, but I can't find any information about what size of that frames and does it possible to set it?

Have anybody met this restriction and what is the right way? Just increase the **maxReceivedFrameSize**?
I did it, it works, but It will occupy all memory if you try to send huge data(

And one more, when a browser sends data with amount more than maxReceivedFrameSize the WebSocketServer break connection without any errors, only with 'close' event.

Just for quick test Client-Server-Client: [Drag and Drop image.zip](https://github.com/theturtle32/WebSocket-Node/files/531475/ws_drag_drop_img.zip)

**Comment by theturtle32** [comment]
Yes, you need to increase this value to accommodate the kinds of data frames you expect your application to send to the server. Designing your application not to send huge messages in order to avoid taxing the server's memory is your own responsibility.
