### ISSUE TITLE
Install gives error node-gyp rebuild 2

### ISSUE THREAD

**Issue by videobuff** [theturtle32/WebSocket-Node#268]
When I install websocket (npm 3.10.10) i get the following error.
# npm install -g websocket

> websocket@1.0.23 install /root/.node_modules_global/lib/node_modules/websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

I have followed several threads (installed node-gyp & socket.io) bo to no avail.
Machine is Raspberry Pi.
OS:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

**Comment by sweplatte** [comment]
Same.

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "websocket"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! file /Users/nick/Projects/novel-backend13/blow-logs/processor/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Trailing comma in object at 14:3
npm ERR!   }
npm ERR!   ^
npm ERR! File: /Users/nick/Projects/novel-backend13/blow-logs/processor/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by d3x0r** [comment]
so what's in builderror.log; it's not an error; it's redirecting stderr to builderror.log

**Comment by ibc** [comment]
Please if you want to report an issue, just report the issue. There is no issue nor error log above.
