### ISSUE TITLE
Moz obsolete, no? also docs and readme misalign

### ISSUE THREAD

**Issue by MasterJames** [theturtle32/WebSocket-Node#270]
Isn't MozWebSocket an obsolete concept? It's a nice example but maybe another super simple, as in minimalist's simplest possible example, is a nice idea. At least in the readme, which shows nodejs to nodejs and kind of seems to skip a basic browser example (I'm left thinking maybe that's the point without saying so off the get go? or point here for client example https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_client_applications or https://developer.mozilla.org/en-US/docs/Web/API/WebSocket)
https://github.com/theturtle32/WebSocket-Node/blob/master/example/whiteboard/public/client.js

I also noted )got confused because( you have this var WebSocketRouter = require('websocket').router and then it's missing from the docs https://github.com/theturtle32/WebSocket-Node/blob/master/docs/index.md

I also thought this was websockets/ws because of the npm names seem mixed up, maybe readme links there for clarity is another thought to consider.

location.hostname is also a better suggestion over document.URL.substr(7) IMO

You can just close this after taken note. Thanks for the package.

**Comment by theturtle32** [comment]
Yeah I need to update the example.
