### ISSUE TITLE
FancyWebSocket doesn't work with SSL protocal

### ISSUE THREAD

**Issue by truedandyman** [theturtle32/WebSocket-Node#271]
Hi,
Now I have an issue with SSL and WebSocket.
I use Xampp on Windows and I created self signed Certificate.
I set the websocket server url as "wss://192.168.3.103:9300" and add the configuration on http-ssl.conf as same as default_443.(just copy and paste it and changed port as 9300).
And the Jquery part is following.
`if ( typeof(MozWebSocket) == 'function' )`
      `this.conn = new MozWebSocket(url);`
`else`
      `this.conn = new WebSocket(url);`

But the send part has an error

> InvalidStateError : An attempt was made to use an object that is not, or is no longer, usable.
The code is:
`this.send = function(event_name, event_data){
     this.conn.send(event_data);
     return this;
};`

So I modified the FancyWebSocket.js file as following:
`this.conn = new MozWebSocket(url, {
	protocolVersion: 8,
	origin: 'https://192.168.3.103:443',
	rejectUnauthorized: false
} );`

But the browser says : 
> SyntaxError: An invalid or illegal string was specified

Help me please,,,,
Thanks

**Comment by ibc** [comment]
We don't know what `FancyWebSocket` is.

```js
this.conn = new MozWebSocket(url, { protocolVersion: 8, origin: 'https://192.168.3.103:443', rejectUnauthorized: false } );
```

No idea why you are using such a wrong API into a browser.

Your issue does not seem to be related to this library.

**Comment by IaMArcomonreal** [comment]
> Hi,
> Now I have an issue with SSL and WebSocket.
> I use Xampp on Windows and I created self signed Certificate.
> I set the websocket server url as "wss://192.168.3.103:9300" and add the configuration on http-ssl.conf as same as default_443.(just copy and paste it and changed port as 9300).
> And the Jquery part is following.
> `if ( typeof(MozWebSocket) == 'function' )`
> `this.conn = new MozWebSocket(url);`
> `else`
> `this.conn = new WebSocket(url);`
> 
> But the send part has an error
> 
> > InvalidStateError : An attempt was made to use an object that is not, or is no longer, usable.
> > The code is:
> > `this.send = function(event_name, event_data){      this.conn.send(event_data);      return this; };`
> 
> So I modified the FancyWebSocket.js file as following:
> `this.conn = new MozWebSocket(url, { protocolVersion: 8, origin: 'https://192.168.3.103:443', rejectUnauthorized: false } );`
> 
> But the browser says :
> 
> > SyntaxError: An invalid or illegal string was specified
> 
> Help me please,,,,
> Thanks


hello friend, could you solve the problem?
