### ISSUE TITLE
WebSocketClient is not a constructor

### ISSUE THREAD

**Issue by moriczgergo** [theturtle32/WebSocket-Node#276]
I am using `browserify` to run `lgtv` in the browser, and `lgtv` uses `websocket.client` for communication with TV.

However, when I use the bundled .js that was given to me by `browserify`, I got this error:
`Uncaught TypeError: WebSocketClient is not a constructor`

Here is some code from the bundled .js file:
```
var WebSocketClient = require('websocket').client; // for communication with TV
var client = new WebSocketClient();
```

The problematic line is this:
`var client = new WebSocketClient();`

Can anyone help?

**Comment by ibc** [comment]
Can you check/log what `WebSocketClient` is?

**Comment by braytak** [comment]
Works for me!
V 1.0.24

Le jeu. 9 mars 2017 16:51, Iñaki Baz Castillo <notifications@github.com> a
écrit :

**Comment by moriczgergo** [comment]
@ibc It sais "client is not defined"
Error on this line:
`var WebSocketClient = require('websocket').client;`

**Comment by moriczgergo** [comment]
@braytak Tried websocket 1.0.24, still this error :/

**Comment by isurugajasinghe** [comment]
Still have a same issue. Pls check and let me know pls

**Comment by BobCaSUaL** [comment]
Still have a same issue

**Comment by tlaukkan** [comment]
w3cwebsocket class works:

var W3CWebSocket = require('websocket').w3cwebsocket;

**Comment by cute-angelia** [comment]
Still have a same issue

**Comment by stone89son** [comment]
Still have a same issue

**Comment by ibc** [comment]
Guys, in browser you cannot use WebSocketClient class as it's just for Node (it uses Node stuff not available in the browser).

In the browser you should just use the native WebSocket class. And, just if you are developing an app that must run in browser and Node and must behave as a WebSocket client, then use:

var W3CWebSocket = require('websocket').w3cwebsocket;

In fact, when in the browser, such a W3CWebSocket class is just an alias to the native browser WebSocket class. And in Node it's just a wrapper over Node-WebSocket.WebSocketClient that offers an API similar to the W3 WebSocket class in the browser.

**Comment by stone89son** [comment]
thank you.

**Comment by tarunjuneja** [comment]
to all future debugger - until today i.e 15-07-21

Browser also don't support sending customer headers to the server, so any such code

```
        import * as sock from 'websocket'
        const headers = {
            Authorization: "bearer " + token
        };
        console.log(headers);

        const wsclient = new sock.w3cwebsocket(
            'wss://' + server + '/diagnostics/api/1/diagnostics/log/session1234',
            '',
            '',
            headers,
            null
        );

```

This is not going to work in browser. The reason behind that is browser native Websocket constructor does not accept headers.

You can easily get misguided because w3cwebsocket contractor accepts headers as i have shown above. This works in node.js however.
