### ISSUE TITLE
Weird characters on websocket.send()

### ISSUE THREAD

**Issue by timgrossmann** [theturtle32/WebSocket-Node#280]
When sending anything with a Websocket.Server instance, I always get the answer like this 
```�{"success":true}��```
> This was the **String** { "success": true }

No matter what I send with `ws.send` (where websocket is the server instance), I always get these weird characters. Even with an empty call 
` ���`
> This was a completely empty send() call

Any idea on how to get rid of this?
Thanks

**Comment by braytak** [comment]
Please provide a working code snippet that reproduces the issue.

**Comment by timgrossmann** [comment]
Sadly, I can't... The code is pretty complex and property of the company.

I thought maybe someone already had this kind of an issue....

**Comment by braytak** [comment]
Well then allow me to speculate... 
Looks like the server is framing whatever you are sending... 

Suggestion... run the client with developer tools to look at the frame character codes; see if they are the same whatever the source string... 

Maybe that can provide a hint to whom wrote the server code...

Hope this helps

**Comment by timgrossmann** [comment]
Well, just tested it in the browser and it works there...

But when I use the curl command from this gist: https://gist.github.com/htp/fbce19069187ec1cc486b594104f01d0 to invoke the websocket it get the weird characters...

Does anyone have any idea on how to "better" start a websocket connection from the terminal?

**Comment by ibc** [comment]
Well, here you are assuming that WebSocket works fine via `curl` command. It may, or not. Probably it doesn't.

Please, ensure that you are testing the WebSocket-Node library rather than Curl.
