### ISSUE TITLE
N-API Support for websocket

### ISSUE THREAD

**Issue by sampsongao** [theturtle32/WebSocket-Node#284]
The recently announced Node 8 has a new experimental feature called N-API which is aimed at reducing maintenance cost for node native addons. Checkout this blog for more details on its benefits.

Module `websocket` is one of the top 30 native modules by dependency count, and in order to help the Node.js community make the important transition to N-API, we are hoping you will be able to work with us in order to port `websocket` to support N-API. Your support and feedback is important in making this effort a success.

I am part of the N-API working group and and would like to talk to you about how you can can get started with N-API and what help we might be able to provide. I'm available to talk on the phone individually if you'd like. Alternatively, if you prefer, feel free to jump in our [WG meeting](https://plus.google.com/u/0/events/c0eevtrlajniu7h8cjrdk0f56c8?authkey=COH04YCalJS8Ug) which happens every Thursday at 1.30 Eastern / 10.30 Pacific US time, to discuss any issues.

[Here](https://www.youtube.com/watch?v=nmXhJ88nZsk)’s a video of N-API in action

**Comment by theturtle32** [comment]
I'm currently on vacation in Hawaii. Will have to check into this sometime
when I get back! :-D

Brian

**Comment by sampsongao** [comment]
Hi @theturtle32, have you come back from your vacation yet?

**Comment by andreek** [comment]
@sampsongao 
Both native modules used in this lib are extracted from https://github.com/websockets/ws. 
Today these native modules are available as packages. See https://github.com/websockets/bufferutil / https://github.com/websockets/utf-8-validate.

It would be better if this lib could be refactored to use the packages as dependencies. Instead of porting to N-API in two places.

**Comment by sampsongao** [comment]
Hi @andreek, are you managing the https://github.com/websockets/ws repo? We would happy to help porting this module to N-API.

**Comment by andreek** [comment]
@sampsongao No, I'm just interested in N-API and started here. I've a complete port for [utf-8-validate](https://github.com/websockets/utf-8-validate) as fork [here](https://github.com/andreek/utf-8-validate). I'll send the websockets team later a PR asking if they may want have it as branch in their repo.

**Comment by andreek** [comment]
This issue can be closed.
