### ISSUE TITLE
require('webwocket').client fails if _global returns undefined (browser.js:1)

### ISSUE THREAD

**Issue by jhudson8** [theturtle32/WebSocket-Node#287]
I'm using webpack v2 to bundle my app and I'm not sure why but the `this` in the following code block
```javascript
var _global = (function() { return this; })();
```
returns undefined which causes the following error
```
Uncaught TypeError: Cannot read property 'WebSocket' of undefined
```
https://github.com/theturtle32/WebSocket-Node/blob/master/lib/browser.js#L1

To resolve this, I added the following code
```javascript
var _global = (function() {
  if (!this && typeof global !== 'undefined') {
    return global;
  }
  return this;
})();
```

**Comment by ibc** [comment]
Interesting. I don't understand why webpack v2 fails on that line but your approach seems legit to me.

Can you send a PR, please?
