### ISSUE TITLE
Infinite _tickCallback loop related to handleSocketError()

### ISSUE THREAD

**Issue by tvkit** [theturtle32/WebSocket-Node#288]
Upon socket error, the socket notifies (WebSocketConnection) `handleSocketErrror()`. In turn, `handleSocketError()` proceeds to destroy the socket. In turn, the socket notifies `handleSocketErrror()` about its destruction, and so on...

Checking for `STATE_CLOSED` within [handleSocketErrror()](https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketConnection.js#L334) could mitigate the infinite loop which is executing via Node's  [_tickCallback()](https://github.com/nodejs/node/blob/master/lib/internal/process/next_tick.js#L151).  Refer to [handleSocketEnd()](https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketConnection.js#L351)

Node 8.1.4
WebSocket-Node 1.0.24 (Released 2016-12-28)

Callstack:

```

nextTick [next_tick.js] Line 233	JavaScript
destroy [destroy.js] Line 15	JavaScript
WebSocketConnection.handleSocketError [WebSocketConnection.js] Line 344	JavaScript
emitOne [events.js] Line 115	JavaScript
emit [events.js] Line 210	JavaScript
emitErrorNT [destroy.js] Line 62	JavaScript
_combinedTickCallback [next_tick.js] Line 102	JavaScript
_tickCallback [next_tick.js] Line 161	JavaScript

```

**Comment by guillemsola** [comment]
I have the very same issue. Launching clients if one of them subscribes to the OnError event, after the socket has been closed by the other party the event is executed forever until (in some seconds) the machine runs out of heap memory making it crash.

The proposed patch from @tvkit rather fixes this behavior although IMO a proper design of the events emitted should be desirable.

**Comment by ibc** [comment]
Oh! could this be the same as #294??

**Comment by MariaDima** [comment]
Thanks for the fix!
Could you please make a release to include it in an official version?

**Comment by tvkit** [comment]
@MariaDima, already merged. See:  https://github.com/theturtle32/WebSocket-Node/pull/289

**Comment by MariaDima** [comment]
Thanks a lot @tvkit !
I was checking the github releases and missed it :-)!
