### ISSUE TITLE
Browser example?

### ISSUE THREAD

**Issue by superqd** [theturtle32/WebSocket-Node#298]
Are there any examples of getting this to work in the browser?  I am using a 3rd party API to connect to their websocket endpoint, but it returns a redirect.  But the native WebSocket in the browser doesn't support redirects, and the 3rd party just told me to find a library that does. 

I came across your library, but don't see any browser examples.  I tried running browserify (first time I used it), and it failed cause it looks like it's looking for native files too (I tried pointing it at the main websocket file, and also at index.js, etc).

Do you guys have an browser examples, or builds, of the code?

**Comment by ibc** [comment]
A browser cannot run "another" WebSocket implementation, but just its native one.

**Comment by superqd** [comment]
You did not actually address my question.  Do you have any examples of getting your code to run in a browser?

**Comment by ibc** [comment]
I did answer. This library (`WebSocket-Node`) is a WebSocket implementation for Node, not for browsers. You just cannot implement a "WebSocket stack" for browsers. Browsers provide their native WebSocket implementations.

> Do you have any examples of getting your code to run in a browser?

The question does not make sense due the rationale given above. If you want a response anyway, it's "no".
