### ISSUE TITLE
Sending large Frame in webSocket causing WebSocket close

### ISSUE THREAD

**Issue by bahamut657** [theturtle32/WebSocket-Node#301]
I notice that if the webSocketClient (i'm using the W3C implementation, but I''ve checked that the problem is in WebSocketConnection.js row 298) receives a large packet, the implementation drop the connection managing ("FRAME TOO LARGE") 
This product is not stable to work at all....

**Comment by ibc** [comment]
Maybe you should read the documentation and set the proper settings rather than stating that "this product is not stable at all".
