### ISSUE TITLE
autoAcceptConnections and CORS

### ISSUE THREAD

**Issue by aakilfernandes** [theturtle32/WebSocket-Node#305]
I have a question about `autoAcceptConnections`

```
    // You should not use autoAcceptConnections for production
    // applications, as it defeats all standard cross-origin protection
    // facilities built into the protocol and the browser.  You should
    // *always* verify the connection's origin and decide whether or not
    // to accept it.
    autoAcceptConnections: false
```

I'm working on a protocol that should allow users to connect from any origin. Is there any reason *not* to turn this off other than origin?

**Comment by theturtle32** [comment]
You should be fine if you explicitly don't want to validate the origin. I just feel it's best practice to write an explicit handler to analyze the request and validate it before accepting the connection.
