### ISSUE TITLE
Error 1009,,message size too big

### ISSUE THREAD

**Issue by abbadabbatech** [theturtle32/WebSocket-Node#307]
I have tried to set the server config of maxReceivedMessageSize, but continue to get this error, the message is way under the size I set but it is over the default.  Have you seen this or had this reported?

`var wsServer = new webSocketServer ({
    httpServer: server,
    maxReceivedMessageSize: 10*1024*1024*1024,
    maxReceivedFrameSize: 131072
});`

**Comment by MuhammadAli-208** [comment]
getting closed websocket connection with code 1009 and reason **Frame size of 131000 bytes exceeds maximum accepted frame size**
