### ISSUE TITLE
[WSS] WebSocket connection failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by Preta-Crowz** [theturtle32/WebSocket-Node#318]
```js
const Const = require('../const')
const File = require('fs')

module.exports = () => {
    const options = {};
    if(Const.SSL_OPTIONS.isPFX == true) {
        options.pfx = File.readFileSync(Const.SSL_OPTIONS.PFX);
        options.passphrase = Const.SSL_OPTIONS.PFXPass;
    } else {
        options.key = File.readFileSync(Const.SSL_OPTIONS.PRIVKEY);
        options.cert = File.readFileSync(Const.SSL_OPTIONS.CERT);
        if(Const.SSL_OPTIONS.isCA == true) {
            options.ca = File.readFileSync(Const.SSL_OPTIONS.CA);
        }
    }
    return options;
}
```
▲ secure.js / webinit.js ▼
```js
const options = Secure();
HTTPS_Server = https.createServer(options)
	.listen(global.test ? (Const.TEST_PORT + 416) : process.env['KKUTU_PORT']);
Server = new WebSocket.Server({server: HTTPS_Server});
```

When I tried to connect websocket, it raises `ERR_CERT_AUTHORITY_INVALID`

**Comment by ibc** [comment]
Not a bug in WebSocket-Node. Check your cert. If auto-signed you may need additional stuff in your code (and not within WebSocket-Node) to make it work.

**Comment by soulbeing** [comment]
@ibc Can you provide some examples of what you meant by additional stuff? There's not much documents around, can you provide more details, please?

**Comment by adavidof** [comment]
@ibc friendly ping :)
could you please provide some examples of additional stuff?

**Comment by Harpreetsinghbedi** [comment]
Hi,

I have same issue. [WSS] WebSocket connection failed: Error in connection establishment: net::ERR_CERT_AUTHORITY_INVALID

Could you please help me to resolve this issue?

Thanks

**Comment by salmansaleem32** [comment]
Hi, any update on this issue ?

**Comment by baalan92** [comment]
I am also having the issue in Laravel

**Comment by Sarmed-armis** [comment]
same issue  with me here

**Comment by Harpreetsinghbedi** [comment]
Hi,
I have fixed this issue via using CA certificate.

I get my host certificate and install it with my computer to fix it.
