### ISSUE TITLE
w3cwebsocket set headers invalid

### ISSUE THREAD

**Issue by ywww** [theturtle32/WebSocket-Node#321]
const w3cwebsocket = require('websocket').w3cwebsocket;
new w3cwebsocket(this.props.url, null, null, {'token': 'aaaa'}, null)

but request do not has token header

Host: 127.0.0.1:8885
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
Origin: http://192.168.25.21:8080
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9
Cookie: JSESSIONID=654795A3AFD8A1CEC8AFE379FDD9889E
Sec-WebSocket-Key: /P40OPR/r/MHhx28Eol8JQ==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

**Comment by ywww** [comment]
w3cwebsocket set headers  do not work

**Comment by ibc** [comment]
Where are you running the above code? in a Node.js script/server? or in a browser JS?

**Comment by ywww** [comment]
in a browser JS

**Comment by ibc** [comment]
No. No JS library can add extra headers in WebSocket in a browser. The Websocket standard/API does not allow it.
