### ISSUE TITLE
Send message to client

### ISSUE THREAD

**Issue by Gerrymandered** [theturtle32/WebSocket-Node#324]
Is it possible for the server to send a message to a specific client? If so, how would I go about that?

**Comment by ibc** [comment]
Please, read the API documentation.

**Comment by Gerrymandered** [comment]
@ibc can I at least get a link to know where to look?

**Comment by saulpalv** [comment]
extend declaration for typescript
```
declare module 'websocket' {
    interface connection {
        id?: string
    }
}
```

then 

```
this.connection = request.accept()
this.connection.id == uuidV4()
```
