### ISSUE TITLE
issues when used with https / nginx

### ISSUE THREAD

**Issue by ryan-morris** [theturtle32/WebSocket-Node#341]
When I try to create a client connection with the below

```
const WebSocketClient = require('websocket').client;
const client = new WebSocketClient();
client.connect('https://domain.com/ws', 'echo-protocol', null, { 'x-api-key': 'key' }, { });
```

I get the following error
```
Connect Error: Error: Server responded with a non-101 status: 400 Bad Request
Response Headers Follow:
server: nginx/1.14.1
date: Tue, 08 Jan 2019 21:48:52 GMT
content-type: text/html
content-length: 271
connection: close
```

and in nginx I see 

`client sent plain HTTP request to HTTPS port while reading client request headers`

**Comment by ibc** [comment]
This is not a problem in WebSocket-Node but in your Nginx configuration. Configure it properly to accept WebSocket connections.

**Comment by ryan-morris** [comment]
@ibc If I connect with `client.connect('wss://domain.com/ws', 'echo-protocol', null, { 'x-api-key': 'key' }, { });`, everything works properly, nginx is only configured to connect with `listen 443 ssl` and the location block

```

**Comment by ibc** [comment]
Well, it makes sense (as the [doc](https://github.com/theturtle32/WebSocket-Node/blob/master/docs/WebSocketClient.md#methods) states).
`client.connect()` expects a `ws` or `wss` URI and not a `https` one.
