### ISSUE TITLE
.git folder included in the npm distribution

### ISSUE THREAD

**Issue by jonknight73** [theturtle32/WebSocket-Node#353]
The presence of a .git folder means that the npm install errors out when run for the second time of a project as below:

```bash
npm ERR! path ... /node_modules/websocket
npm ERR! code EISGIT
npm ERR! git ... /node_modules/websocket: Appears to be a git repo or submodule.
npm ERR! git ... /node_modules/websocket
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

Manually deleting the .git folder fixes it. 

Could you please remove the .git folder from the distribution?

**Comment by ibc** [comment]
Thanks, fixed.
@theturtle32 may you do a release please?

**Comment by jonknight73** [comment]
Thank you. That was stunningly rapid.

**Comment by Gudahtt** [comment]
@theturtle32 just wanted to remind you that this change is still awaiting release. If you could find the time, it would be greatly appreciated!

**Comment by CarlosLanderas** [comment]
Please, release the package with this fix... 
It is breaking a lot of installs

**Comment by theturtle32** [comment]
Fixed.

**Comment by theturtle32** [comment]
Released

**Comment by CarlosLanderas** [comment]
Thanks @theturtle32

**Comment by michaelsbradleyjr** [comment]
Normally it's not necessary to ignore `.git/`. For those who ran into this bug and are puzzled as to what was happening, see: https://github.com/npm/npm-packlist/issues/35.

So an alternative fix would have been to change [`"main": "index",`](https://github.com/theturtle32/WebSocket-Node/blob/master/package.json#L52) to `"main": "index.js",`.
