### ISSUE TITLE
`close` even is not fired when calling `connection.close()` method

### ISSUE THREAD

**Issue by nazar-pc** [theturtle32/WebSocket-Node#354]
Found this very counter-intuitive and had to write a workaround, would be nice to see this fixed upstream

**Comment by ibc** [comment]
Actually there is nothing to fix. Firing events as a result os direct actions on an object (such as calling `close()` on it) is not a mandatory design.

If you wish to improve the documentation feel free to send a PR.

**Comment by nazar-pc** [comment]
The problem was that I had event handler that I expect to always be called when connection is closed. And I've seen the same behavior from multiple libraries. But here it was rather confusing and it is hard for me to see how this can be beneficial to anyone at all. Sure, this is not mandatory, but it would so nice to have. Maybe consider changing behavior in the next version?

**Comment by ibc** [comment]
Personally I do not like that calling a method in an object fires an event in the same object. If I know that I'm doing something I do not need an out-of-context event to tell me that.

Honestly I don't think this is gonna change, neither I think it should change (but that's just my opinion).

**Comment by nazar-pc** [comment]
Could the fact that native Node.js sockets pretty much follow this paradigm?:
```javascript
const dgram = require("dgram");
const net = require("net");

const udp4Socket = dgram.createSocket('udp4');
udp4Socket
    .on('close', () => {
        console.log('UDP closed');
    })
    .bind(() => {
        udp4Socket.close();
    });


const tcpServer = net.createServer();
tcpServer.listen(() => {
    const address = tcpServer.address();
    const tcpSocket = net.createConnection(address.port, address.address);
    tcpSocket
        .on('connect', () => {
            tcpSocket.end();
        })
        .on('close', () => {
            console.log('TCP closed');
            tcpServer.close();
        });
});
```

There are often things like cleanup that you have to do regardless of why connection was closed. And with this library besides calling `connection.close()` I also always need to call yet another function to make sure everything is cleaned up. If I forget to do that (and I did when I didn't know about this unexpected behavior) there will likely be a memory leak.

Please consider rectifying this.
