### ISSUE TITLE
ERR! Command failed (Команда не выполнена): git checkout 4.0

### ISSUE THREAD

**Issue by VNS65** [theturtle32/WebSocket-Node#356]
Ошибка `npm ERR! Command failed: git checkout 4.0` при установке **websocket**.

```cmd
npm ERR! code 1
npm ERR! Command failed: git checkout 4.0
npm ERR! error: pathspec '4.0' did not match any file(s) known to git
npm ERR!

```

**Решение**:

Заменить в `path/to/node_modules/websocket/package.json` линия 57: 
`"gulp": "git+https://github.com/gulpjs/gulp.git#4.0"` на `"gulp": "^4.0"`

В корне `path/to/node_modules/websocket` запустить команду `npm i`.

Бонусом можно включить параллельное построение `node-gyp`, параметр `/m` .
```json
"scripts": {
  "gulp": "gulp",
  "install": "(node-gyp rebuild /m 2> builderror.log) || (exit 0)",
  "test": "faucet test/unit"
}
```

**Comment by ibc** [comment]
Please, write in English.

BTW the issue has been fixed in https://github.com/theturtle32/WebSocket-Node/commit/3cb29e1041ecca0a9c21f809890204271900f6f6.

@theturtle32 can you make a new release pleasE?
