### ISSUE TITLE
Write the library in TypeScript?

### ISSUE THREAD

**Issue by ORESoftware** [theturtle32/WebSocket-Node#367]
I am looking for a WebSockets library written in TypeScript

https://www.quora.com/unanswered/Is-there-a-Websocket-library-for-Node-js-written-in-TypeScript

it looks like @types/ws exists, but since it's packaged separately, often the types become out-of-sync.

**Comment by ibc** [comment]
`ws` is a different WebSocket library, so unrelated to this project.

If you want to provide TypeScript definitions for this project, don't hesitase to send a PR. Asking for others to do it is not the way to go.

**Comment by nazar-pc** [comment]
There are TypeScript definitions already in `@types/websocket`, but having them in this repo would be better obviously

**Comment by ORESoftware** [comment]
Just write the lib in TS, I swear you can do it in 2 hours, and the benefit would be for the lifetime of the library

**Comment by nazar-pc** [comment]
Honestly, it is not possible to write such library in TypeScript or any other language in 2 hours. And rewrite would take much longer too.
But I would definitely be in favor of TypeScript implementation, it is so much easier to maintain and work with. But that is up to maintainers to decide.

**Comment by ibc** [comment]
> Just write the lib in TS, I swear you can do it in 2 hours, and the benefit would be for the lifetime of the library

Do it yourself then.

**Comment by ORESoftware** [comment]
Well I looked at the codebase, I was confusing this one with another, it would take more than 2 hours :) Maybe 2 days.
