### ISSUE TITLE
if url is "https://" websocket client does not use TLS on connection

### ISSUE THREAD

**Issue by davehorton** [theturtle32/WebSocket-Node#368]
I note that a url beginning with "wss://" causes an SSL connection to be made, but a url beginning with "https://" causes an http connection to be made from the WebSocket.Client

**Comment by ibc** [comment]
WebSocket URIs have "ws" or "wss" scheme and not "http" or "https". You MUST NOT use "http" or "https".

**Comment by davehorton** [comment]
In that case, I think that WebSocket.Client should assert or throw an Error (with a useful message).....as opposed to sending an http request, which is what it does now

**Comment by ibc** [comment]
Yes, it may do it. But wrong API usage may produce undetermined behavior. There is absolutely zero reasons to use a HTTP schema in a API that expects a WebSocket schema.
