### ISSUE TITLE
How to implement the concepts of rooms in websocket

### ISSUE THREAD

**Issue by hunzalashakeel1996** [theturtle32/WebSocket-Node#370]
hi. currently i am working on a project which use websocket. I have a knowledge of socket.io and creating rooms in socket.io. But in websockets i can't find solution for creating rooms. Is there any way or  workaround to create rooms in websockets.

**Comment by ibc** [comment]
WebSocket-Node is a low level WS library. "Rooms" are application specific. Easily achievable with a few lines of JS.
