### ISSUE TITLE
npm install on Windows 10 

### ISSUE THREAD

**Issue by gernotziegler** [theturtle32/WebSocket-Node#374]
Hi, I am getting the following compilation error when trying to install websocket on node.js version 12.8 in Windows 10, x64 (Visual Studio 2017 should be installed; python 3.4 - maybe that is the issue?): 

D:\www\tensordraco>npm install -g websocket

> websocket@1.0.30 install C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)

C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Users\gernot\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\gernot\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
  win_delay_load_hook.cc
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(34): error C2660: 'v8::FunctionTemplate::G
etFunction': function does not take 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\buffe
rutil.vcxproj]
  c:\users\gernot\appdata\local\node-gyp\cache\12.8.0\include\node\v8.h(5955): note: see declaration of 'v8::FunctionTe
  mplate::GetFunction' (compiling source file ..\src\bufferutil.cc)
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(34): error C2661: 'Nan::Set': no overloade
d function takes 2 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\bufferutil.vcxproj]
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(50): error C2661: 'v8::Value::ToObject': n
o overloaded function takes 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\bufferutil.vc
xproj]
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(57): error C2661: 'v8::Value::ToObject': n
o overloaded function takes 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\bufferutil.vc
xproj]
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(68): error C2661: 'v8::Value::ToObject': n
o overloaded function takes 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\bufferutil.vc
xproj]
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(70): error C2661: 'v8::Value::ToObject': n
o overloaded function takes 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\bufferutil.vc
xproj]
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(89): error C2661: 'v8::Value::ToObject': n
o overloaded function takes 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\bufferutil.vc
xproj]
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(90): error C2661: 'v8::Value::ToObject': n
o overloaded function takes 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\bufferutil.vc
xproj]
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(92): error C2661: 'v8::Value::ToObject': n
o overloaded function takes 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\bufferutil.vc
xproj]
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(93): error C2660: 'v8::Value::Int32Value':
 function does not take 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\bufferutil.vcxpro
j]
  c:\users\gernot\appdata\local\node-gyp\cache\12.8.0\include\node\v8.h(2576): note: see declaration of 'v8::Value::Int
  32Value' (compiling source file ..\src\bufferutil.cc)
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\bufferutil.cc(94): error C2660: 'v8::Value::Int32Value':
 function does not take 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\bufferutil.vcxpro
j]
  c:\users\gernot\appdata\local\node-gyp\cache\12.8.0\include\node\v8.h(2576): note: see declaration of 'v8::Value::Int
  32Value' (compiling source file ..\src\bufferutil.cc)
  validation.cc
  win_delay_load_hook.cc
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\validation.cc(114): error C2660: 'v8::FunctionTemplate::
GetFunction': function does not take 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\vali
dation.vcxproj]
  c:\users\gernot\appdata\local\node-gyp\cache\12.8.0\include\node\v8.h(5955): note: see declaration of 'v8::FunctionTe
  mplate::GetFunction' (compiling source file ..\src\validation.cc)
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\validation.cc(114): error C2661: 'Nan::Set': no overload
ed function takes 2 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\validation.vcxproj]
c:\users\gernot\appdata\roaming\npm\node_modules\websocket\src\validation.cc(133): error C2661: 'v8::Value::ToObject':
no overloaded function takes 0 arguments [C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\validation.v
cxproj]
+ websocket@1.0.30
updated 1 package in 4.42s

**Comment by theturtle32** [comment]
Try again with the newly released v1.0.31 and let me know if this is still a problem for you.

**Comment by gernotziegler** [comment]
Now it works. Thank you! 

D:\www\tensordraco>npm install -g websocket

> websocket@1.0.31 install C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket>if not defined npm_config_node_gyp (node "C:\Users\gernot\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\gernot\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  bufferutil.cc
  win_delay_load_hook.cc
     Creating library C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\Release\bufferutil.lib and objec
  t C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\Release\bufferutil.exp
  bufferutil.vcxproj -> C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\Release\\bufferutil.node
  validation.cc
  win_delay_load_hook.cc
     Creating library C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\Release\validation.lib and objec
  t C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\Release\validation.exp
  validation.vcxproj -> C:\Users\gernot\AppData\Roaming\npm\node_modules\websocket\build\Release\\validation.node
+ websocket@1.0.31
added 8 packages from 1 contributor and updated 1 package in 6.03s
