### ISSUE TITLE
build error in nodejs v12

### ISSUE THREAD

**Issue by alex8088** [theturtle32/WebSocket-Node#375]
version: 1.0.30
py: 2.7

bufferutil.cc(34): error C2660: 'v8::FunctionTemplate::GetFunction': function does not take 0 arguments

**Comment by PabloPerezAguilo** [comment]
same with 1.0.29

**Comment by artynet** [comment]
@alex8088 @PabloPerezAguilo   please take a look at my patch and give me some feedback about it

https://github.com/theturtle32/WebSocket-Node/issues/373

it fixes the overall compatibility with V8 release greater or equal than v7.6 (and using the latest nan of course!)

**Comment by PabloPerezAguilo** [comment]
0 Errors
1 Warnings:

\node_modules\web3\src\bufferutil.cc(57): warning C4996: 'v8::Object::Get': se declaró desusado [\node_modules\web3\build\bufferutil.vcxproj]

**Comment by artynet** [comment]
@PabloPerezAguilo glad to know that !

**Comment by theturtle32** [comment]
Fixed in release v1.0.31 on npm.
