### ISSUE TITLE
How to know if connection.sendUTF succeded?

### ISSUE THREAD

**Issue by pSnehanshu** [theturtle32/WebSocket-Node#377]
I want to know if sending messages using `connection.sendUTF` succeeded or not. By looking at the [source code](https://github.com/theturtle32/WebSocket-Node/blob/master/lib/WebSocketConnection.js#L729-L736), i can see that `sendUTF` accepts a second parameter `cb`. I expect `cb` to receive an `error` argument as the first argument if the sending failed. But by testing, it didn't react like that.
Is there any way to know if sending was successful?

**Comment by ibc** [comment]
This is not a WebSocket issue. Please read how the protocol works in the corresponding specification.

**Comment by pSnehanshu** [comment]
`comnection.sendUTF` is a function of this library. I just want to be notified when a message is sent or failed.
