### ISSUE TITLE
WebSocketServer.shutDown() does not trigger connection close events.

### ISSUE THREAD

**Issue by cammil** [theturtle32/WebSocket-Node#381]
It appear that shutDown does not trigger connection close events. Is this expected behaviour?

How should one handle connection closes when they are initiated from WebSocketServer? 

Also, the closure of connections appear to be asynchronous, but there appears to be no way to detect its completion.

BTW, the reason I am asking this is that I am attempting to gracefully shutdown the webserver, and therefore want to handle each connection closure.

**Comment by ibc** [comment]
If you know when you want to shutdown the server you can also call `close()` and all your connections. No need for an event that tells you "hey, you have called server.close()". You already know it.

Yes, there are different approaches but this is quite valid too.
