### ISSUE TITLE
ECONNRESET Error

### ISSUE THREAD

**Issue by shashankbansal21** [theturtle32/WebSocket-Node#383]
Hello, 
My code is working for around 50-60 connections for websockets. But after that some of the sockets receive the below error. 

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)

I verified the file open limit and other networking related stuff, But everything seems good. One of 50 client get this error and continues to reconnect.

**Comment by ibc** [comment]
This means that one of your clients has disconnected, and hence the ECONNRESET error which means exactly that. Not a bug in WebSocket-Node.
