### ISSUE TITLE
How to set route for WebSocket server?

### ISSUE THREAD

**Issue by vijaygopal** [theturtle32/WebSocket-Node#389]
I have an html client and I would like listen to messages to the below path 
ws://localhost:8980/MySampleApp/CarRental

By looking at the server constructor options I didn't find any options? Could you please let me know how to pass a path to the server so that the server listens to that path and not the root path like 'ws://localhost:8980'?

**Comment by vitalets** [comment]
See: https://github.com/theturtle32/WebSocket-Node/issues/245
