### ISSUE TITLE
connection closed on too large arraybuffer

### ISSUE THREAD

**Issue by tvolodimir** [theturtle32/WebSocket-Node#40]
client-side javascript
var size = 65536+1;
var ba = new Uint8Array(size);
for (var i = 0; i < size; i++)  {
   ba[i] = 1;
}
var  m = ba.buffer;
socket.binaryType = 'arraybuffer';
socket.send(m);

server-side javascript
connection.on('message', function(message) {
    if (message.type === 'binary') {
        console.log('Received Binary Message of ' + message.binaryData.length + ' bytes');
        connection.sendBytes(message.binaryData);
    }
});

> Chromium  19.0.1070.0 (Developer Build 126631)
> OS    Windows
> WebKit    536.3 (@110622)
> JavaScript    V8 3.9.13
> Flash 11,1,102,63
> User Agent    Mozilla/5.0 (Windows NT 6.1) AppleWebKit/536.3 (KHTML, like Gecko) Chrome/19.0.1070.0 Safari/536.3

**Comment by SanPilot** [comment]
Hi @tvolodimir 

I'm having this issue now as well, can you tell me how you solved it? I tried setting the config option you mentioned but to no avail. Here's the code I'm using:

    // Start WebSocket server
    var wsServer = new webSocketServer({
      httpServer: server,
      maxRecievedFrameSize: 100000,
      maxRecievedMessageSize: 100000
    });

However, messages of a size over 64KiB, it seems, are still causing the server to end the connection.

cc @theturtle32
