### ISSUE TITLE
binary data

### ISSUE THREAD

**Issue by valkiriy** [theturtle32/WebSocket-Node#410]
Hi all!

Can you help me how a can send data, like this?

![image](https://user-images.githubusercontent.com/1162517/105478335-1e784800-5cb4-11eb-9577-213c866ac42f.png)
--
![image](https://user-images.githubusercontent.com/1162517/105478141-da854300-5cb3-11eb-8636-bf6cc1fdc3a1.png)

**Comment by kuabhish** [comment]
how did you do this?
