### ISSUE TITLE
Best Practice For Re-Using W3CWebsocket Client?

### ISSUE THREAD

**Issue by slimandslam** [theturtle32/WebSocket-Node#428]
Is there a best practice for storing and re-using a websocket client?
Something like this (except that this doesn't seem to work):

```
var client = new W3CWebSocket('ws://localhost:8080/');
sessionStorage.setItem('mysock', JSON.stringify(client));
client = JSON.parse(sessionStorage.getItem('mysock'));
```

The use case is where the user reloads the browser 
window (or goes to another "page" in the same browser window).
The problem is that a new websocket connection is created every
time the user reloads the browser window.
On the server side, we're using websockets via AWS API Gateway

**Comment by ibc** [comment]
I'm afraid this is not even an issue or question related to this library. Closing.

**Comment by slimandslam** [comment]
Hmmm. Well, I'm using the library. And the code above starts with
using this library ("var client = new W3CWebSocket('ws://localhost:8080/')").
So, it's a question about the best way to use this specific feature of the library.

**Comment by ibc** [comment]
No. It's a super generic question about WebSocket usage in browser. The fact that this library exposes a wrapper over the W3C WebSocket API when using it in browser doesn't mean that we should discuss generic WebSocket usage questions by opening issues here in GitHub.
