### ISSUE TITLE
The NPM package is not a place for politics

### ISSUE THREAD

**Issue by eolme** [theturtle32/WebSocket-Node#433]
@ibc WTF wrong with you too?

See: https://github.com/medikoo/es5-ext/issues/113
See: https://github.com/medikoo/es5-ext/issues/114
See: https://github.com/medikoo/es5-ext/issues/115

Related: #432

**Comment by ibc** [comment]
Please stop calling it "politics". It's an invasion. You probably know it because you are well informed.
