### ISSUE TITLE
How to connect to multiple WebSockets?

### ISSUE THREAD

**Issue by sawhitegt3** [theturtle32/WebSocket-Node#440]
Hello. 

 I used the client code on your [npm page](https://www.npmjs.com/package/websocket) as my starting point.  I'm able to connect to the server and everything works great (I'm able to get all the messages that the server sends and process them).

My issue is that when I receive one of the messages, I'm supposed to connect to a different socket that the message provides (it gives me the URI) and close the existing socket.

I'm hoping someone can tell me or point me to some code that will help me understand how to connect to multiple WebSockets.

Also, where can I find a list of all the 'on' methods (like connectFailed, connect, close, message, etc.)?

Thanks for the help, much appreciated!

**Comment by rgillan** [comment]
If you look in the docs folder, there's detail of each of the various functions (client/server etc.).  All of the events are detailed in each of their respective pages.
If I'm understanding correctly, you are connecting a client to a server, it sends you a different URI, so you then need to close the original connection and establish a. new connection to the provided URI?
