### ISSUE TITLE
send to all connected clients

### ISSUE THREAD

**Issue by DeceptiveGmR** [theturtle32/WebSocket-Node#445]
(new to websockets so please forgive my n00bness) I was able to get the nodejs websocket (wss) server up and running with cloudflare and nginx proxy manager. The connection is established and working great. even able to send messages and whatnot. I am currently trying to get the server to receive a message and then relay that message to ALL connected clients. However I am not sure how to accomplish this. I can respond to the sending client, but not all clients. 
If anyone has any information it would be much appreciated!

**Comment by ibc** [comment]
Please don't open an issue to make basic usage questions.

**Comment by DeceptiveGmR** [comment]
> Please don't open an issue to make basic usage questions.

Oh, I'm sorry. I am new to github.
