### ISSUE TITLE
connection.on('message', ...) - where this event is emitted ?

### ISSUE THREAD

**Issue by mir1198yusuf** [theturtle32/WebSocket-Node#449]
Can someone please point me to the source code where `connection.on('message', ...)`, this event is emitted. 
The accept function in the WebSocketRequest file returns WebSocketConnection type object, but there is no handler in that file.

Thanks in advance!

**Comment by rgillan** [comment]
Believe it is in WebSocketConnection, separate emits for binary and text messages depending upon the opCode

WebSocketConnection.prototype.processFrame = function(frame) {

around line 511
