### ISSUE TITLE
Request to Upgrade es5-ext Dependency to Resolve Veracode Vulnerability

### ISSUE THREAD

**Issue by Tringapps-Dharshan** [theturtle32/WebSocket-Node#453]
### Description:
I'm encountering a Veracode vulnerability (Regular Expression Denial of Service - ReDoS) in the `es5-ext` dependency.

### Vulnerability Details:
For more information about the vulnerability, refer to [security.snyk.io](https://security.snyk.io/package/npm/es5-ext).

### Request:
To address this issue, I kindly request an upgrade of the `es5-ext` package to version 0.10.63 or higher to resolve the Veracode vulnerability.

Resolved and pushed the updates to [this pull request](https://github.com/theturtle32/WebSocket-Node/pull/455). Let me know if anything needs further attention.

**Comment by lox** [comment]
Folks might it be possible to get this applied, es5-ext also results in socket.dev scanner errors due to it being protestware: https://github.com/medikoo/es5-ext/issues/116

**Comment by theturtle32** [comment]
For what it's worth, I'm 200% on board with the protestware.

**Comment by lox** [comment]
@theturtle32 I'm building quite sensitive medical software. I have a duty of care to patients that exceeds my political stance here. The addition of a postinstall script in an npm package is a high risk proposition from a supply chain point of view. I fully support the authors right to do what they want with their open source project, I just can't justify including that package in my software.

**Comment by lox** [comment]
Although I realize that this change might have actually done the opposite of what I wanted here.

I've ended up with this in my package.json until I can remove the dependency entirely:

```
  "resolutions": {
    "es5-ext": "0.10.53"
  },
```

**Comment by lox** [comment]
This is what the scanner failures look like now @theturtle32: https://socket.dev/npm/package/websocket
