### ISSUE TITLE
Using WebSocket Secure (wss://) in the browser

### ISSUE THREAD

**Issue by Baggz** [theturtle32/WebSocket-Node#78]
Hi!

I'm having troubles connecting to a WebSocket server via WebSocket Secure connection _(wss://)_ **from the browser**. Standard connections _(ws://)_ work fine.
## ws://

![ws](https://f.cloud.github.com/assets/95191/59838/2cef8f4c-5be6-11e2-9488-f278a6cef5d0.png)
## wss://

![wss](https://f.cloud.github.com/assets/95191/59837/2ceac7be-5be6-11e2-9c69-701f93e49109.png)
## Server

``` javascript
var https = require ('https');
var express = require('express');
var WebSocketServerConstructor = require('websocket').server;

var options = {
  key: ...,
  cert: ...,
  requestCert: true,
  passphrase: ...,
  ca: [
    ...
  ]
};

var Application = express();

var Server = https.createServer(options, Application);

var WebSocketServer = new WebSocketServerConstructor({
  httpServer: Server,
  autoAcceptConnections: true
});

WebSocketServer.on('connect', function(request) {
  console.log('Hello!');
});

Server.listen(443, '0.0.0.0');
```
## Browser

``` javascript
var Socket = new WebSocket('wss://api.example.com/');
```

Is there any way how to establish a secure connection from the browser?

Thanks in advance!

**Comment by cottayson** [comment]
why 443?

**Comment by verteAzur** [comment]
@cottayson  

> why 443?

mostly because it can be accessed behind a firewall...
