### ISSUE TITLE
Can't get websocket-node to work with senchalabs/connect

### ISSUE THREAD

**Issue by braytak** [theturtle32/WebSocket-Node#81]
This is not necessarily an issue...
Tried to follow the same approach as used in one of the examples that uses the express server, but can't seem to get the upgrade to work (no connection established)... 
Both new statements on WebSocketServer (with httpServer option set) and WebSocketRouter return non-null instances.
I have not been able to find any information related to this mashup anywhere.

**Comment by braytak** [comment]
@theturtle32 you may want to get rid of this latent BUG issue since connection upgrade works with the following `server`:

> var express = require('express');
var server = http.createServer(app); 

...idem if you replace *express* with *connect*; since *express* builds on it.

All this when using `websocket@1.0.17`, `connect@3.3.5`, `express@4.12.3` on `node@0.10.26`

:)

**Comment by braytak** [comment]
@theturtle32 
FYI, `connect@3.4.0` works with `websocket@1.0.18` (on `node@0.12.2`)

**Comment by theturtle32** [comment]
Ah ok, thank you!

So to be clear, everything works exactly as expected when using the current versions of express and connect with the current version of websocket?

**Comment by braytak** [comment]
Sure looks like it... At least from my use of it!
I have not tested all midflewares, but Morgan and serve-static work fine.

Le mar. 4 août 2015 17:11, Brian McKelvey <notifications@github.com> a
écrit :

**Comment by theturtle32** [comment]
Alright, sounds good. Thank you!
